table 'Sheet1 (sample_sales_data)'


    column 'Order ID'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Order ID

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Order Date'
        dataType: datetime
        summarizeBy: none
        sourceColumn: Order Date

        annotation SummarizationSetBy = Automatic

        
    column 'Region'
        dataType: string
        summarizeBy: none
        sourceColumn: Region

        annotation SummarizationSetBy = Automatic

        
    column 'Product Category'
        dataType: string
        summarizeBy: none
        sourceColumn: Product Category

        annotation SummarizationSetBy = Automatic

        
    column 'Product Name'
        dataType: string
        summarizeBy: none
        sourceColumn: Product Name

        annotation SummarizationSetBy = Automatic

        
    column 'Sales'
        dataType: double
        summarizeBy: sum
        sourceColumn: Sales

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Quantity'
        dataType: int64
        summarizeBy: sum
        sourceColumn: Quantity

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Discount'
        dataType: double
        summarizeBy: sum
        sourceColumn: Discount

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        
    column 'Profit'
        dataType: double
        summarizeBy: sum
        sourceColumn: Profit

        annotation SummarizationSetBy = User

        annotation PBI_FormatHint = {"isGeneralNumber":true}
        



    partition 'Sheet1 (sample_sales_data)' = m
        mode: import
        source = 
            	let
					Source = Excel.Workbook(File.Contents("C:/Users/CodehiveBIVM/Desktop/Datasets/sample_sales_data.xlsx"), null, true),
					Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
					#"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {})
				in
					#"Changed Type"
        



    annotation PBI_ResultType = Table
