/// Filters the Sales table using sales order date
table Date
	dataCategory: Time

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: string
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: count
		sourceColumn: MonthKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Full Date'
		dataType: string
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Full Date

		annotation SummarizationSetBy = Automatic

	column 'Month Number Of Year'
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Month Number Of Year

		annotation SummarizationSetBy = Automatic

	hierarchy Fiscal

		level Year
			column: 'Fiscal Year'

		level Quarter
			column: 'Fiscal Quarter'

		level Month
			column: Month

		level Date
			column: 'Full Date'

	partition Date-6302b3e1-4d31-40e4-b909-ba364d21aa87 = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_DimDate = Source{[Schema="dbo",Item="DimDate"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_DimDate,{"DateKey", "FullDateAlternateKey", "DayNumberOfMonth", "MonthNumberOfYear", "CalendarYear", "FiscalQuarter", "FiscalYear"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"FullDateAlternateKey", "Date"}, {"FiscalYear", "Fiscal Year"},{"MonthNumberOfYear","Month Number Of Year"}}),
				    #"Added FY Prefix" = Table.TransformColumns(#"Renamed Columns", {{"Fiscal Year", each "FY" & Text.From(_, "en-US"), type text}}),
				    #"Added Fiscal Quarter" = Table.AddColumn(#"Added FY Prefix", "Fiscal Quarter", each [Fiscal Year] & " Q" & Number.ToText([FiscalQuarter])),
				    #"Added Month" = Table.AddColumn(#"Added Fiscal Quarter", "Month", each (Number.ToText([CalendarYear]) & " " & Date.ToText([Date], "MMM", Culture)), type text),
				    #"Added Full Date" = Table.AddColumn(#"Added Month", "Full Date", each [Month] & ", " & Text.PadStart(Number.ToText([DayNumberOfMonth]), 2, "0")),
				    #"Added MonthKey" = Table.AddColumn(#"Added Full Date", "MonthKey", each ([CalendarYear] * 100) + [Month Number Of Year]),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Added MonthKey",{"DateKey", "Date", "Month Number Of Year", "Fiscal Year", "Fiscal Quarter", "Month", "Full Date", "MonthKey"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns1",{{"Fiscal Quarter", type text}, {"Month", type text}, {"Full Date", type text}, {"MonthKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

