table Max\Avg

	column index
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column 'display as'
		dataType: string
		summarizeBy: none
		sourceColumn: display as

		annotation SummarizationSetBy = Automatic

	partition Max\Avg = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlDSUfJNrICSsTrRSoZAtmNZOpSMjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [index = _t, value = _t, #"display as" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"index", Int64.Type}, {"value", type text}, {"display as", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

